### PR TITLE
fix review issues in initial BLS implementation 

### LINKED ISSUE #1911: Fix review comments from PR https://github.com/maidsafe/routing/pull/1906

### PR DESCRIPTION
**Pull request by jeanphilippeD**
Closes #1911 
Fix review issues in #1906 
Also improve handling of malicious inputs not allowing them to break signature combination.

### CODE REVIEW

File: src/chain/chain.rs [hunk 1]
```diff
@@ -1571,6 +1576,55 @@ fn compute_relocation_destination(
         .unwrap_or_else(|| relocation::compute_destination(relocated_name, trigger_name))
 }
 
+#[derive(Clone)]
+/// The secret share of the section key.
+pub struct SectionKeyShare {
```
Comment (octol) [inline src/chain/chain.rs]: Nitpick: is there a convention for doc comment vs `#[]` order? I see it's mixed here...

Comment (madadam) [reply src/chain/chain.rs]: I personally put doc comments first. Not sure that is an established convention though.

**Comment by jeanphilippeD** [comment]
Rebased and address minor review comment.
