### PR TITLE
ensure forward progress of messages with RMD

### LINKED ISSUE #1710: Sometimes fail to send to any targets, or away from section
Running from https://github.com/maidsafe/routing/commit/92944790ee34d681fb76309d899f60d012e3343a
`messages_during_churn` with seed: `Some([2450801160, 1357294273, 3066314373, 3968544834])`

1 - The following show up. This is an issue as we will not send the message.

```
WARN 10:34:40.536494167 [routing::states::common::base base.rs:325] Elder(1638d1..(00)) Less than dg_size valid targets! dg_size = 3; targets = Filter { iter: Iter([]) }; msg = Hop(HopMessage { content: SignedRoutingMessage { content: RoutingMessage { src: PrefixSection(prefix: Prefix(00)), dst: PrefixSection(prefix: Prefix(01)), content: Merge(5f7a85..2b3a48) }, sending nodes: Some(SectionInfo(prefix: Prefix(00), members: {PublicId(name: 1638d1..), PublicId(name: 17cda0..), PublicId(name: 2411d1..)}, prev_hash_len: 1, version: 42)), signatures: ProofSet { [PublicId(name: 1638d1..), PublicId(name: 17cda0..), PublicId(name: 2411d1..)] }, proving_sections: [] }, signature: .. })
```

Investigation suggest that the connected_nodes used during `get_targets` are not necessarily having their connection_info.

2 - Messages for Prefix 0 is initially sent to our own section 10, and then filtered because we already sent them.
```
DEBUG 10:34:48.039060482 [routing::states::elder mod.rs:551] Elder(819236..(10)) Known message: RoutingMessage { src: ManagedNode(name: aa4920..), dst: PrefixSection(prefix: Prefix(0)), content: NeighbourInfo(4f7bea..288f06) } - not handling further
```

This is the reason the test fail at the end:
```
WARN 10:34:48.183600837 [routing::chain::test_utils test_utils.rs:67] A section is below the minimum size: size(Prefix(100)) = 3; For (PublicId(name: 508bd4..): Prefix(0))
WARN 10:34:48.183625315 [routing::chain::test_utils test_utils.rs:67] A section is below the minimum size: size(Prefix(100)) = 3; For (PublicId(name: 5f72f8..): Prefix(0))
WARN 10:34:48.183653209 [routing::chain::test_utils test_utils.rs:67] A section is below the minimum size: size(Prefix(100)) = 3; For (PublicId(name: 4bda7f..): Prefix(0))
WARN 10:34:48.183675882 [routing::chain::test_utils test_utils.rs:67] A section is below the minimum size: size(Prefix(100)) = 3; For (PublicId(name: 17cda0..): Prefix(0))
WARN 10:34:48.183701838 [routing::chain::test_utils test_utils.rs:67] A section is below the minimum size: size(Prefix(100)) = 3; For (PublicId(name: 5293ff..): Prefix(0))
WARN 10:34:48.183721131 [routing::chain::test_utils test_utils.rs:67] A section is below the minimum size: size(Prefix(100)) = 3; For (PublicId(name: 53c9d8..): Prefix(0))
WARN 10:34:48.183740664 [routing::chain::test_utils test_utils.rs:67] A section is below the minimum size: size(Prefix(100)) = 3; For (PublicId(name: 3d728b..): Prefix(0))
WARN 10:34:48.183770318 [routing::chain::test_utils test_utils.rs:67] A section is below the minimum size: size(Prefix(100)) = 3; For (PublicId(name: 4e3e7d..): Prefix(0))
WARN 10:34:48.183802266 [routing::chain::test_utils test_utils.rs:67] A section is below the minimum size: size(Prefix(100)) = 3; For (PublicId(name: 5ccb2b..): Prefix(0))
WARN 10:34:48.183819621 [routing::chain::test_utils test_utils.rs:67] A section is below the minimum size: size(Prefix(100)) = 3; For (PublicId(name: 110bf6..): Prefix(0))
test mock_network::churn::messages_during_churn ... FAILED

failures:

---- mock_network::churn::messages_during_churn stdout ----
RNG seed: Some([2450801160, 1357294273, 3066314373, 3968544834])
thread 'mock_network::churn::messages_during_churn' panicked at 'Section prefixes should be disjoint, but these are not:
Section Prefix(10), according to node eea089..: SectionInfo(prefix: Prefix(10), members: {PublicId(name: 819236..), PublicId(name: 861d80..), PublicId(name: 8f3b78..), PublicId(name: a6f335..), PublicId(name: aa4920..), PublicId(name: ac3d8b..), PublicId(name: bd0cc3..)}, prev_hash_len: 2, version: 56)
Section Prefix(100), according to node 508bd4..: SectionInfo(prefix: Prefix(100), members: {PublicId(name: 819236..), PublicId(name: 861d80..), PublicId(name: 8f3b78..)}, prev_hash_len: 1, version: 54)', src/chain/test_utils.rs:179:17
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

The problem may be that we are not sufficiently connected to the section 0 that is our neighbor from (10). But we are sending to a subset of peers from our section that are also not sufficiently connected.

Assuming at least one good node from our section is sufficiently connected, we should send it to all our peers so that node can do the send (and not a subset).
Additionally, if one of our node is even partially connected, we should probably send the message forward as well as to our other peers so that we can recover from low connectivity.

FYI @fizyk20 @Lindsey17

### LINKED ISSUE #1727: Failure to deliver message when not well connected
At commit 11358bcf27a74d405ceb61711d4a0e2951de360d  we got a soak test seed failure for Reliable Message Delivery.

On this particular seed, the NodeApproval message is sent to the 1st hop, but then that hop try to send it to itself instead of the next hop, and then drop the message as already seen.
This can happen when the relay node is not well connected enough with the next section, then the best section is ourselves.

To fix this we probably need to do a few things:
-Consider all the node we can communicate with (in peer_map) as connected.
-When resending to our section, we probably want to send to all our nodes so if one is better connected it can forward the message.
-These 2 steps were implemented in https://github.com/jeanphilippeD/routing/tree/try_fix_to_silence_issue and were not enough: When resending to our section because not well connected enough we will probably also want to send to any node that we were connected to from the best destination. But we may also want to send to other sections that may be better connected.

Slack chat:
```
Stephen Coyle  4 hours ago
Morning guys, got a new FAILURE in the soak tests for PR 1725 overnight:

---- mock_network::churn::messages_during_churn stdout ----
thread 'mock_network::churn::messages_during_churn' panicked at 'Non-empty set of failed nodes! Failed nodes: [40380d..]', tests/mock_network/churn.rs:613:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

====================================================
Some([1354155478, 1967105506, 274954128, 642718695])
====================================================


Jean-Philippe Dufraigne  1 hour ago
I don't think this is related to this PR 1725.
I am looking at it and it seems to be an RMD issue. (using the latest version of the PR)
Again NodeApproval seem to not be delivered.What we get in the debug message is that the section that has more than 3 connections is ourselves, then we send to ourselves and eventually filter the message out.

DEBUG 12:04:14.858929984 [routing::states::elder mod.rs:1349] Elder(5006bc..(010)): Sending message RoutingMessage { src: PrefixSection(prefix: Prefix(010)), dst: Client { client_name: 40380d.., proxy_node_name: acf68f.. }, content: NodeApproval { GenesisPfxInfo(Prefix(010), gen_version: 22, latest_version: 23) } } via targets [PublicId(name: c922d2..), PublicId(name: cbb972..), PublicId(name: c70a25..), PublicId(name: c2ef9c..), PublicId(name: c39e17..), PublicId(name: df79aa..), PublicId(name: d9a93e..), PublicId(name: d4e486..), PublicId(name: d7243d..), PublicId(name: d70ac9..)]

I was trying to solve that issue before with https://github.com/jeanphilippeD/routing/tree/try_fix_to_silence_issue but it did not completely fix the issue.
I think what I was thinking was missing at the time was we should also add targets from the section that we are not sufficiently connected too as well so the message is delivered.I'll add some logs to clarify what exactly is the connection situation when that happen with this seed.@bart and idea comment on the approach?


Bartłomiej Kamiński:desktop_computer:  1 hour ago

    What we get in the debug message is that the section that has more than 3 connections is ourselves, then we send to ourselves and eventually filter the message out.

I don't really get that, can you elaborate?
The debug message you posted seems to indicate that a sender in section 010 tries to send to 10 (or 101, not sure what sections are there, but the target starts with a, so 1010...) via 110. Not sure what you mean by sending to ourselves?


Jean-Philippe Dufraigne  1 hour ago
You are correct, I pasted the wrong debug line.
The problem occur on the second hop.

DEBUG 12:04:15.174285315 [routing::states::elder mod.rs:1349] Elder(c70a25..(110)): Sending message RoutingMessage { src: PrefixSection(prefix: Prefix(010)), dst: Client { client_name: 40380d.., proxy_node_name: acf68f.. }, content: NodeApproval { GenesisPfxInfo(Prefix(010), gen_version: 22, latest_version: 23) } } via targets [PublicId(name: c922d2..), PublicId(name: cbb972..), PublicId(name: c2ef9c..), PublicId(name: c39e17..), PublicId(name: df79aa..), PublicId(name: d9a93e..), PublicId(name: d4e486..), PublicId(name: d7243d..), PublicId(name: d70ac9..)]

...

DEBUG 12:04:15.282836050 [routing::states::elder mod.rs:553] Elder(c922d2..(110)) Known message: RoutingMessage { src: PrefixSection(prefix: Prefix(010)), dst: Client { client_name: 40380d.., proxy_node_name: acf68f.. }, content: NodeApproval { GenesisPfxInfo(Prefix(010), gen_version: 22, latest_version: 23) } } - not handling further



Bartłomiej Kamiński:desktop_computer:  1 hour ago
I see...
Maybe what we should do would be to ignore who we are connected to? The idea with quic-p2p is that we should be able to make connections on the fly, so maybe if we know that we should be sending to another section, we should just do it and connect as needed? That should also fix the problem, shouldn't it?


Jean-Philippe Dufraigne  1 hour ago
Possibly, but I believe we still need the connection info though, which I don't think we have if we are not connected (so the peer in the peer_map).
I think this is what that commit part of the 2 commit attempt was trying to do, I think: https://github.com/jeanphilippeD/routing/commit/a8fe858980ebf1c574336241b85512c83e03c3f5

            let conn_peers = self
                .peer_map()
                .connected_ids()
                .map(|pub_id| pub_id.name())
                .chain(iter::once(self.name()))
                .collect_vec();

so i still think that if we are not connected to all the nodes we still need to be able to send a RoutingMessage to get their connection info.


Jean-Philippe Dufraigne  32 minutes ago
I'll create an issue for it, it is probably best for me to focus on finishing SharedState first as it is going to block you.

```

### PR DESCRIPTION
**Pull request by jeanphilippeD**
Closes #1727 
Closes #1710

### CODE REVIEW

File: src/chain/chain.rs [hunk 1]
```diff
@@ -996,29 +996,44 @@ impl Chain {
...
-                )
-            })
+
+            let mut dg_size = 0;
+            let mut node_to_send = Vec::new();
+            for (idx, (prefix, len, connected)) in filtered_sections.enumerate() {
+                node_to_send.extend(connected.into_iter());
+                dg_size = delivery_group_size(len);
+
+                if &prefix == self.our_prefix() {
```
Comment (maqi) [inline src/chain/chain.rs]: just to confirm. So if our section is not the closest (i.e. idx!=0), then we will need to send to all the sections closer to it than us and the self section. But no more than that.
right?
Probably the comment of `Send to all connected nodes so the connected node can forward the message` is bit misleading, as here the nodes that connected but is far than us, doesn't need be to send to ?

File: src/chain/chain.rs [hunk 2]
```diff
@@ -996,29 +996,44 @@ impl Chain {
...
+                    break;
+                }
+                if idx == 0 && node_to_send.len() >= dg_size {
+                    // can deliver to enough of the closest section
+                    break;
+                }
+            }
+            node_to_send.sort_by(|lhs, rhs| target_name.cmp_distance(lhs, rhs));
+
+            if dg_size > 0 && dg_size <= node_to_send.len() {
```
Comment (maqi) [inline src/chain/chain.rs]: in case of idx==0, we break at `dg_size >= node_to_send.len()`
however here we are looking for `dg_size <= node_to_send.len()`,
doesn't it mean only the case of `dg_size == node_to_send.len()` will pass ?

File: src/states/elder/mod.rs [hunk 3]
```diff
@@ -1438,7 +1438,12 @@ impl Elder {
             // TODO: even if having chain reply based on connected_state,
             // we remove self in targets info and can do same by not
             // chaining us to conn_peer list here?
-            let conn_peers = self.connected_peers();
```
Comment (maqi) [inline src/states/elder/mod.rs]: hmm...
so previously we use the function from peer_manager, and now it's fetched from the peer_map's forward.keys.
does it mean the source is different now? if so, maybe better change a name to avoid mis-use?

File: src/chain/chain.rs (hunk 1 above)
Comment (jeanphilippeD) [reply src/chain/chain.rs]: I could replace node with target.

`Send to all connected targets so they can forward the message`

File: src/chain/chain.rs (hunk 2 above)
Comment (jeanphilippeD) [reply src/chain/chain.rs]:
```
dg_size = 3
node_to_send.len() = 8
idx = 0

if idx == 0 && node_to_send.len() >= dg_size   --> This is true, so break
if dg_size > 0 && dg_size <= node_to_send.len()  --> this is true so return Ok.
```

File: src/states/elder/mod.rs (hunk 3 above)
Comment (jeanphilippeD) [reply src/states/elder/mod.rs]: This is still the connected peers, and in most case both are the same.
However, the one in peer_map is the one used to get the connection info to actually send the message, so this ensure we use the same valid set.

File: src/chain/chain.rs (hunk 2 above)
Comment (maqi) [reply src/chain/chain.rs]: ah, ok, the position of `dg_size` is flipped
maybe make it appear at the same front position?

**Comment by jeanphilippeD** [comment]
Fixed review comments

File: src/chain/chain.rs [hunk 4]
```diff
@@ -996,29 +996,44 @@ impl Chain {
...
+                node_to_send.extend(connected.into_iter());
+                dg_size = delivery_group_size(len);
+
+                if &prefix == self.our_prefix() {
+                    // Send to all connected targets so they can forward the message
+                    node_to_send.retain(|&x| x != *self.our_id().name());
+                    dg_size = node_to_send.len();
+                    break;
+                }
+                if idx == 0 && node_to_send.len() >= dg_size {
```
Comment (fizyk20) [inline src/chain/chain.rs]: Does it make sense to check the index here? I mean, if the number of candidate nodes exceeds `dg_size`, then we're fine regardless of whether that's the first section on the list or not, aren't we?

File: src/chain/chain.rs [hunk 5]
```diff
@@ -996,29 +996,44 @@ impl Chain {
...
-                (
-                    len,
-                    connected
-                        .into_iter()
-                        .sorted_by(|lhs, rhs| target_name.cmp_distance(lhs, rhs)),
-                )
-            })
+
+            let mut dg_size = 0;
+            let mut node_to_send = Vec::new();
```
Comment (fizyk20) [inline src/chain/chain.rs]: Should we call it `nodes_to_send`? This is a list, not a single node, after all.

File: src/chain/chain.rs (hunk 4 above)
Comment (jeanphilippeD) [reply src/chain/chain.rs]: I guess this would be more efficient (do we need it though since that should rarely happen / does not seem to impact test performance as well).
But we would have to be careful, i.e we cannot just remove `idx == 0`, because if we use a delivery group, the node to send need to only contain nodes from a single section.

In this case we would need to first check:
```rust
let group_dg_size = delivery_group_size(len);
let is_our_prefix = &prefix == self.our_prefix();
if !is_our_prefix && connected.len() >= group_dg_size {
     // Only send to that group since it is forward progress.
     node_to_send = connected;
     dg_size = delivery_group_size(group_dg_size);
     break;
}
if is_our_prefix {
     // Send to all connected targets so they can forward the message
     node_to_send.retain(|&x| x != *self.our_id().name());
     dg_size = node_to_send.len();
     break; 
}
```

I'm not 100% sure it is simpler/better.

In the current implementation, we either have the normal case where we send to delivery group from 3 peers, and if one of them is not connected enough it will send to everyone closer that them + own section (yes, that can be quite spammy)

In the alternative, we either have the normal case where we send to delivery group from 3 peers, and if one of them is not connected enough it will send to another section that is closer but connected enough, and if none such exist, it will send to everyone closer than them + own section (yes, that would be the same spammy, but in fewer cases).

Is that what you had in mind?

Comment (jeanphilippeD) [reply src/chain/chain.rs]: I think I still favor the current implementation.

**Comment by jeanphilippeD** [comment]
Fixed minor review comment

File: src/chain/chain.rs (hunk 4 above)
Comment (fizyk20) [reply src/chain/chain.rs]: > it will send to everyone closer that them + own section (yes, that can be quite spammy)
Ah, I missed this part. Yeah, that is spammy, but it should be an unusual case, so maybe not that big of a problem.
Anyway, it makes more sense now, so I'm okay with leaving it as is :+1:
