### PR TITLE
fix performance issue following PR 1705

### LINKED ISSUE #1684: Resend messages on failure (how does routing pick the new recipient?)
=> When receiving send_failure from the networking layer, routing will need to pick a different relay target

=> The destination may be picked based on state we have when receiving failure. We may need to maintain some cached info abt the member state when attempting to send the msg…

Dependent on https://github.com/maidsafe/routing/issues/1681

### PR DESCRIPTION
**Pull request by jeanphilippeD**
Closes #1684

Because of additional messages sent, soak test experienced a performance hit.
Remove main bottle neck for performance that came from previous way of establishing trust that is disabled currently and will be replace by Secure Message Delivery.

### CODE REVIEW

**Comment by jeanphilippeD** [comment]
Added new commit to fix soak test failure.

**Comment by jeanphilippeD** [comment]
Rebase and updated PR comment and title.

File: src/states/elder/mod.rs [hunk 1]
```diff
@@ -2158,9 +2147,15 @@ impl Approved for Elder {
...
-        if validates(&trusted, &sec_info) || self.is_trusted(&sec_info)? {
-            let _ = self.add_new_section(&sec_info);
+        if !(validates(&trusted, &sec_info) || self.is_trusted(&sec_info)?) {
+            trace!(
+                "{} Adding untrusted neighbour section info {:?}",
+                self,
+                &sec_info
+            );
         }
+        // Always add section info until SMD is complete
```
Comment (maqi) [inline src/states/elder/mod.rs]: shall we have a TODO keyword here to highlight?

File: src/states/elder/mod.rs [hunk 2]
```diff
@@ -2158,9 +2147,15 @@ impl Approved for Elder {
                 trusted = Some(ps);
             }
         }
-        if validates(&trusted, &sec_info) || self.is_trusted(&sec_info)? {
-            let _ = self.add_new_section(&sec_info);
+        if !(validates(&trusted, &sec_info) || self.is_trusted(&sec_info)?) {
+            trace!(
```
Comment (maqi) [inline src/states/elder/mod.rs]: so this branch now becomes for logging purpose only?
shall we put it under a `debug` guard to save the computation?

Comment (jeanphilippeD) [reply src/states/elder/mod.rs]: No need, we will have to change all that code to be secure with SMD, also unless profiling showed a problem we should not do these kind of optimization. Also log is used in release mode :-)

File: src/states/elder/mod.rs (hunk 1 above)
Comment (jeanphilippeD) [reply src/states/elder/mod.rs]: I prefer to be cautious with TODO as they quickly become outdated, essentially the TODO would be implement SMD.
We will definitely need to update this code for SMD, otherwise test that validate that we reject invalid update should fail.

Comment (maqi) [reply src/states/elder/mod.rs]: I suggest to use a keyword of `TODO` just for a highlight so we won't forget to update this place of code (and the comment as well).
If you think it won't be forgot for sure, I am ok with leave it.  :)

**Comment by jeanphilippeD** [comment]
Added TODO comment.
