### PR TITLE
test/routing: verify message with invalid signature will be blocked

### LINKED ISSUE #1765: Test: Add test injecting messages with invalid signatures.
(Init est 3-4 days)

We should have some integration test that cover that we do not behave wrongly if additional malicious messages without valid signature that we trust are send, or some messages are replayed...

### PR DESCRIPTION
**Pull request by maqi**
Closes #1765

### CODE REVIEW

File: src/chain/section_info.rs [hunk 1]
```diff
@@ -83,26 +83,32 @@ impl SectionInfo {
         Self::new(members, self.prefix.popped(), vec![self, other])
     }
 
+    /// Returns the reference of the members.
```
Comment (fizyk20) [inline src/chain/section_info.rs]: Maybe "Returns a reference to the set of members"?

File: src/chain/section_info.rs [hunk 2]
```diff
@@ -83,26 +83,32 @@ impl SectionInfo {
...
     pub fn members(&self) -> &BTreeSet<PublicId> {
         &self.members
     }
 
+    /// Returns the `XorName`s of the members.
     pub fn member_names(&self) -> BTreeSet<XorName> {
         self.members.iter().map(PublicId::name).cloned().collect()
     }
 
+    /// Returns the version of this sectio info.
```
Comment (fizyk20) [inline src/chain/section_info.rs]: Typo: "sectio"

File: src/states/elder/mod.rs [hunk 3]
```diff
@@ -1792,6 +1794,19 @@ impl Elder {
...
     }
+
+    pub fn send_msg_to_targets(
+        &mut self,
+        dst_targets: &[PublicId],
+        dg_size: usize,
+        message: Message,
+    ) {
+        self.send_message_to_targets(dst_targets, dg_size, message)
+    }
```
Comment (fizyk20) [inline src/states/elder/mod.rs]: Is this function necessary? Can't we just call `send_message_to_targets` directly wherever we're calling this function?

File: tests/mock_network/secure_message_delivery.rs [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+        .collect_vec();
+    let src = Authority::Section(ori_prefix.name());
+    let dst = Authority::PrefixSection(other_prefixes[0]);
+    let content = MessageContent::NeighbourInfo(new_info.clone());
+
+    let routing_msg = RoutingMessage { src, dst, content };
+
+    let proof = unwrap!(nodes[0].inner.chain()).prove(&dst);
+    let pk_set = BlsPublicKeySet::from_section_info(new_info);
+    let signed_msg = unwrap!(SignedRoutingMessage::new(
```
Comment (jeanphilippeD) [inline tests/mock_network/secure_message_delivery.rs]: So this Create a Partial security_metadata.
Could probably just use a completely unrealted BLS Key that you create in the test instead of trying to get one from the node (should be simpler).

File: tests/mock_network/secure_message_delivery.rs [hunk 5]
```diff
@@ -0,0 +1,69 @@
...
+    let _ = members.insert(pub_id);
+
+    let new_info = unwrap!(SectionInfo::new_with_fields(
+        members.clone(),
+        ori_info.version() + 1,
+        ori_prefix,
+        BTreeSet::new(),
+    ));
+
+    let other_prefixes: Vec<_> = unwrap!(nodes[0].inner.chain())
```
Comment (jeanphilippeD) [inline tests/mock_network/secure_message_delivery.rs]: Probably no need to go through this hoop, could just send to the our_prefix().sibling().
Or it could be easier to send to a single node, that is nodes[0] with a message with a built up SectionInfo?

File: tests/mock_network/secure_message_delivery.rs [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+    let mut nodes = create_connected_nodes_until_split(&network, vec![1, 1], false);
+
+    let ori_info = unwrap!(nodes[0].inner.chain()).our_info().clone();
+    let ori_prefix = *ori_info.prefix();
+
+    let mut members = ori_info.members().clone();
+    let pub_id = *FullId::new().public_id();
+    let _ = members.insert(pub_id);
+
+    let new_info = unwrap!(SectionInfo::new_with_fields(
```
Comment (jeanphilippeD) [inline tests/mock_network/secure_message_delivery.rs]: could use new_for_test

File: tests/mock_network/secure_message_delivery.rs [hunk 7]
```diff
@@ -0,0 +1,69 @@
...
+        routing_msg,
+        unwrap!(nodes[0].inner.node_state()).get_full_id(),
+        pk_set,
+        proof
+    ));
+
+    let neighbour_infos: Vec<_> = unwrap!(nodes[0].inner.chain())
+        .neighbour_infos()
+        .collect_vec();
+    let targets = neighbour_infos[0].members().iter().copied().collect_vec();
```
Comment (jeanphilippeD) [inline tests/mock_network/secure_message_delivery.rs]: Probably can send to a single node. For that matter, the initial target could be the node[0], which should then send to the right section through RMD.

File: tests/mock_network/secure_message_delivery.rs (hunk 4 above)
Comment (maqi) [reply tests/mock_network/secure_message_delivery.rs]: just pushed a tryout commit which composes full security_metadata.
need to confirm whether the setup is correct

File: tests/mock_network/secure_message_delivery.rs (hunk 5 above)
Comment (maqi) [reply tests/mock_network/secure_message_delivery.rs]: will have a try

File: src/states/elder/mod.rs (hunk 3 above)
Comment (maqi) [reply src/states/elder/mod.rs]: The `send_message_to_targets` is defined under that `Base` trait.
Trying to use it means need to expose `Base` as public too, which incurs many comments to be added to those pub functions.  :(

Comment (jeanphilippeD) [reply src/states/elder/mod.rs]: also it is for testing purpose only, so not really something we want in pub interface

File: tests/mock_network/secure_message_delivery.rs [hunk 8]
```diff
@@ -0,0 +1,82 @@
...
+fn message_with_invalid_signature() {
+    let min_section_size = 3;
+    let network = Network::new(min_section_size, None);
+    let mut nodes = create_connected_nodes_until_split(&network, vec![1, 1], false);
+
+    let ori_info = unwrap!(nodes[0].inner.chain()).our_info().clone();
+    let ori_prefix = *ori_info.prefix();
+
+    let mut members = ori_info.members().clone();
+    let pub_id = *FullId::new().public_id();
```
Comment (fizyk20) [inline tests/mock_network/secure_message_delivery.rs]: Maybe you could try saving the full ID here, then adding it's signature share to the message, too, before combining the signatures? (if there are still problems with the test)

File: src/chain/mod.rs [hunk 9]
```diff
@@ -50,3 +53,25 @@ impl Debug for GenesisPfxInfo {
...
 }
+
+#[cfg(feature = "mock_base")]
+/// Test helper to create arbitrary proof.
+pub fn section_proof_chain_from_section_info(section_info: &SectionInfo) -> SectionProofChain {
+    SectionProofChain::from_genesis(SectionKeyInfo::from_section_info(&section_info))
+}
+
+#[cfg(feature = "mock_base")]
+/// Test helper to create arbitrary proof.
```
Comment (jeanphilippeD) [inline src/chain/mod.rs]: Need update

File: src/chain/mod.rs [hunk 10]
```diff
@@ -50,3 +53,25 @@ impl Debug for GenesisPfxInfo {
...
+pub fn bls_key_set_from_section_info(section_info: SectionInfo) -> BlsPublicKeySet {
+    BlsPublicKeySet::from_section_info(section_info)
+}
+
+#[cfg(feature = "mock_base")]
+/// Test helper to create arbitrary proof.
```
Comment (jeanphilippeD) [inline src/chain/mod.rs]: Need update
