### PR TITLE
Implement relocation trigger + fix relocation proof handling

### LINKED ISSUE #1858: Implement relocation trigger
We currently increment the age counters on each churn event. When such increment causes some nodes age to increase (`log2(age_counter)` becomes whole number), we should relocate those nodes. The relocation destinations should be calculated by hashing the churn event + the node name.

### LINKED ISSUE #1859: Optimize relocation
Currently (when #1848 is merged), the relocation works like this:

1. The section votes to relocate a node
2. When the vote accumulates, they send a routing message (`Section` -> `Node`) to the node to be relocated
3. The node receives the message and uses it, together with its security metadata, as a proof for the target section that the relocation is genuine.

We can optimize it like this:

1. The section votes to relocate a node like before, but each vote now includes a BLS signature share of the relocate details.
2. When the vote accumulates, the sig shares are combined to form full BLS signature. That + the current `SectionBlockChain` is used as the proof for the target section
3. ~~No additional message needs to be sent to the node-to-be-relocated, because that node too receives the accumulated vote and can act on it~~
If the node to-be-relocated is elder, it will also receive the vote, so no additional message needs to be sent to it. Otherwise a simple `DirectMessage` with the relocate details + the signature and proof is sent to it.
4. The remaining nodes can then immediately remove and disconnect the relocated node. There is no need for the delayed disconnection hack we currently use as there are no more messages sent to the node

### PR DESCRIPTION
**Pull request by madadam**
This PR implement relocation trigger based on churn events according to #1858. It also fixes a flaw in the current relocation logic where the section proof chain sent to the target section was incorrectly calculated and would result in the trust check failing if the target section was sufficiently far away from the source section (e.g. not neighbour). 

Closes #1858 
Closes #1859

### CODE REVIEW

File: src/states/elder/mod.rs [hunk 1]
```diff
@@ -857,9 +841,15 @@ impl Elder {
         self.vote_for_network_event(event.into_network_event())
     }
 
-    fn vote_for_section_info(&mut self, info: EldersInfo) -> Result<(), RoutingError> {
-        let signature_payload = SectionInfoSigPayload::new(&info, &self.full_id)?;
-        self.vote_for_network_event(info.into_network_event_with(Some(signature_payload)));
+    fn vote_for_signed_event<T: IntoAccumulatingEvent + Serialize>(
```
Comment (jeanphilippeD) [inline src/states/elder/mod.rs]: Possibly worth having 2 named functions for the different events, it does help with searching for when things are voted, particularly the section_info one.

File: src/states/elder/mod.rs [hunk 2]
```diff
@@ -1558,29 +1579,20 @@ impl Approved for Elder {
...
-    fn handle_relocate_event(&mut self, payload: RelocateDetails) -> Result<(), RoutingError> {
+    fn handle_relocate_event(
+        &mut self,
+        payload: RelocateDetails,
+        signature: BlsSignature,
+    ) -> Result<(), RoutingError> {
         info!("{} - handle Relocate: {:?}.", self, payload);
 
         let pub_id = payload.pub_id;
+        let proof = self.chain.prove(&Authority::Section(payload.destination));
```
Comment (jeanphilippeD) [inline src/states/elder/mod.rs]: If you want the payload to be checked by both the destination and the relocating node, it might be necessary to create 2 proofs (one for each), or one proof that is the max of both.

SMD will then give you some guarantee that any elder receiving it will be able to validate it, however we might also need to cater for adult eventually and that may require a longer proof for the Adult to verify (don't know how we'll do that but we'll have to track what our adults trust of us).

Comment (madadam) [reply src/states/elder/mod.rs]: If the proof good for the destination section, doesn't that mean it is also good for the source section, since the source section needs only the latest link in the proof chain anyway?

Comment (jeanphilippeD) [reply src/states/elder/mod.rs]: No, there is not such guarantee, (though it is likely that it will be so). 
One source Elder may be lagging behind (and showed up in test), as a result self section message go through the same process of AckMessage with themselves.

For example the destination section may already have sent the AckMessage, but one elder in the source section have yet to reach the new SectionInfo in consensus.

File: src/states/bootstrapping_peer.rs [hunk 3]
```diff
@@ -363,7 +371,7 @@ impl Base for BootstrappingPeer {
                 Ok(Transition::Stay)
             }
             _ => {
-                debug!("{} - Unhandled direct message: {:?}", self, msg);
+                trace!("{} - Unhandled direct message: {:?}", self, msg);
```
Comment (jeanphilippeD) [inline src/states/bootstrapping_peer.rs]: Why this change: Are we getting a lot of messages because other nodes still think we are in previous section?
Is that going to cause problem, (i.e that is why I added the backlog from joining peer etc, because otherwise messages were being dropped).

File: src/states/common/approved.rs [hunk 4]
```diff
@@ -252,7 +257,12 @@ pub trait Approved: Base {
 
     fn chain_poll(&mut self, outbox: &mut dyn EventBox) -> Result<Transition, RoutingError> {
         let mut our_pfx = *self.chain_mut().our_prefix();
-        while let Some((event, neighbour_change)) = self.chain_mut().poll()? {
+        while let Some(AccumulatedEvent {
```
Comment (jeanphilippeD) [inline src/states/common/approved.rs]: would it make sense to not de-structure here, and use `match accumulated_event.event` or is it not working?

File: src/states/common/approved.rs [hunk 5]
```diff
@@ -296,7 +306,18 @@ pub trait Approved: Base {
                         self, event
                     );
                 }
-                AccumulatingEvent::Relocate(payload) => self.handle_relocate_event(payload)?,
+                AccumulatingEvent::Relocate(payload) => {
+                    if let Some(signature) = signature {
```
Comment (jeanphilippeD) [inline src/states/common/approved.rs]: Would it make sense to have a subfunction here to do that check & log_or_panic since that function is big?

File: src/states/elder/mod.rs [hunk 6]
```diff
@@ -75,34 +72,30 @@ pub struct ElderDetails {
...
     full_id: FullId,
     is_first_node: bool,
-    /// The queue of routing messages addressed to us. These do not themselves need forwarding,
-    /// although they may wrap a message which needs forwarding.
+    // The queue of routing messages addressed to us. These do not themselves need forwarding,
+    // although they may wrap a message which needs forwarding.
     msg_queue: VecDeque<SignedRoutingMessage>,
     routing_msg_backlog: Vec<SignedRoutingMessage>,
     direct_msg_backlog: Vec<(P2pNode, DirectMessage)>,
+    relocate_backlog: VecDeque<RelocateDetails>,
```
Comment (jeanphilippeD) [inline src/states/elder/mod.rs]: I'm not 100% sure this is the right place for this `relocate_backlog`.
1 - This is probably something we want as shared state between all Elders.
   => This needs to be at least in chain, but really better in shared_state.
   => i.e if we have some relocate backlog, and a new Elder, we want it to vote on it too.

2 - I'm thinking that most of the work for this should probably be in the chain.
  => Since we are triggering relocation when churn happen, might be good to always push it into backlog at the point we increase_age. Then we probably would want to do the vote in a function called from Approved::chain_poll (not sure how that fit, it could come out of `.chain_mut().poll()` i.e either AccumulatedEvent or something else.) I think that would be shared state. Would also leave us more option into when to do the relocation, do we want to process all online/offline consensused first?

File: tests/mock_network/node_ageing.rs [hunk 7]
```diff
@@ -116,19 +132,17 @@ fn relocate_causing_split() {
 #[ignore]
```
Comment (jeanphilippeD) [inline tests/mock_network/node_ageing.rs]: Should the new id of the joining node be in the sub-prefix that contain the relocation destination (i.e either a prefix with one more bit that the one we knew, or even a few more bits (maybe 3)).

File: src/states/bootstrapping_peer.rs (hunk 3 above)
Comment (madadam) [reply src/states/bootstrapping_peer.rs]: Didn't think this message was important enough to be more than trace. Don't mind changing it back if you disagree.

Comment (jeanphilippeD) [reply src/states/bootstrapping_peer.rs]: I'm ok either way, i tend to debug with `trace` anyway because otherwise I always got something missing. For me this is more important than `we got that message`, because it can be the root cause of why a message does not reach its destination. So i tend to treat these more carefully.

I was more wondering if there was a change with this PR that made this message appear a lot, and if so if that was OK.

File: src/chain/chain.rs [hunk 8]
```diff
@@ -79,6 +65,8 @@ pub struct Chain {
     parsec_prune_accumulated: usize,
     /// Marker indicating we are processing churn event
     churn_in_progress: bool,
+    /// Pending relocations.
+    relocate_queue: VecDeque<RelocateDetails>,
```
Comment (jeanphilippeD) [inline src/chain/chain.rs]: Question why is it ok in Chain and not needed in SharedState?

File: tests/mock_network/node_ageing.rs (hunk 7 above)
Comment (madadam) [reply tests/mock_network/node_ageing.rs]: Interesting idea. I guess there is always some probability that the section splits multiple times by the time the relocated node joins, but that probability rapidly decreases with each bit added, so this seem like a decent fix. I would address this in a separate PR though, if you don't mind.

Comment (madadam) [reply tests/mock_network/node_ageing.rs]: There was already an issue for this: https://github.com/maidsafe/routing/issues/1861 - I added your idea there.

File: src/chain/chain.rs [hunk 9]
```diff
@@ -444,33 +464,59 @@ impl Chain {
...
-        // to elder.
-        self.churn_in_progress = true;
-
         let pub_id = *p2p_node.public_id();
 
-        // Note: it's important that `increment_age_counters` is called *after* the node is added.
+        match self.state.our_members.entry(pub_id) {
+            Entry::Occupied(mut entry) => {
+                if entry.get().state == MemberState::Left {
+                    // Node rejoining
```
Comment (jeanphilippeD) [inline src/chain/chain.rs]: Why do we have a node rejoining as part of this PR? Should it not never happen (i.e when relocate even on same section change ID?

File: src/chain/shared_state.rs [hunk 10]
```diff
@@ -275,12 +275,17 @@ impl SharedState {
...
+    /// Remove items that are no longer relevant after a prefix change.
+    pub fn handle_prefix_change(&mut self, prefix: &Prefix<XorName>) {
+        // Prune our_members
         self.our_members = mem::replace(&mut self.our_members, BTreeMap::new())
             .into_iter()
             .filter(|(pub_id, _)| prefix.matches(pub_id.name()))
             .collect();
+
+        // Prune relocate_queue
+        self.relocate_queue
```
Comment (jeanphilippeD) [inline src/chain/shared_state.rs]: Do we really want to do it here? for online node we do it when processing the event.
Question, what happen if a node was pushed in the relocate queue, but then removed before this could be processed, would you not have to handled node not there anyway?

File: src/chain/chain.rs (hunk 9 above)
Comment (madadam) [reply src/chain/chain.rs]: We don't really do node rejoining yet. The rejoining node will still start as infant. That's why I added the TODO below to remind us to implement proper rejoining.

You are right that this branch is currently never going to be entered, but the behaviour is not changed from before this PR, the code is just more explicit now (previously we did this implicitly via `or_insert_with(...)`).

File: src/chain/shared_state.rs (hunk 10 above)
Comment (madadam) [reply src/chain/shared_state.rs]: It's not strictly necessary to do it here, but it avoids the unnecessary work of voting `Relocate` and letting it accumulate for nodes that are no longer in our section. 

 > Question, what happen if a node was pushed in the relocate queue, but then removed

This is not handled currently, so we would still vote `Relocate`, let it accumulate and only then ignore it due to the node not being a member anymore.

Should I maybe implement the check inside `poll_relocation` instead, to handle both cases? What do you think?

File: src/states/elder/mod.rs [hunk 11]
```diff
@@ -914,9 +883,21 @@ impl Elder {
         self.vote_for_network_event(event.into_network_event())
     }
 
-    fn vote_for_section_info(&mut self, info: EldersInfo) -> Result<(), RoutingError> {
-        let signature_payload = SectionInfoSigPayload::new(&info, &self.full_id)?;
-        self.vote_for_network_event(info.into_network_event_with(Some(signature_payload)));
+    fn vote_for_relocate(&mut self, details: RelocateDetails) -> Result<(), RoutingError> {
+        // trace!("{} - Relocating {}", self, details.pub_id);
```
Comment (fizyk20) [inline src/states/elder/mod.rs]: Should this line be removed?

File: src/states/elder/mod.rs [hunk 12]
```diff
@@ -1575,6 +1561,10 @@ impl Approved for Elder {
             });
 
             self.send_neighbour_infos();
+
+            if let Some(relocate_details) = self.chain.poll_relocation() {
+                self.vote_for_relocate(relocate_details)?;
+            }
```
Comment (fizyk20) [inline src/states/elder/mod.rs]: Why are we voting here in addition to when we process `Online`/`Offline`? Every `Online` and `Offline` will generate a new `SectionInfo` event, anyway (at least until we have proper promotions/demotions). Or is the purpose to enable relocating more than one node per churn event?

File: src/states/elder/mod.rs [hunk 13]
```diff
@@ -1607,27 +1597,43 @@ impl Approved for Elder {
...
+        let proof = {
+            let proof_for_source = self.chain.prove(&Authority::Node(*details.pub_id.name()));
+            let proof_for_target = self.chain.prove(&Authority::Section(details.destination));
+
+            if proof_for_source.blocks_len() > proof_for_target.blocks_len() {
+                proof_for_source
+            } else {
+                proof_for_target
+            }
+        };
```
Comment (fizyk20) [inline src/states/elder/mod.rs]: This could use a comment. I understand that we are taking the longer proof, but I'm not sure why. Is it because the longer one will be correct for both the source and the target? If yes, is it guaranteed to be so?

File: src/chain/chain.rs [hunk 14]
```diff
@@ -1467,10 +1497,63 @@ impl Chain {
 
 #[cfg(feature = "mock_base")]
 impl Chain {
+    /// Returns our section info with the given hash, if it exists.
+    pub fn our_info_by_hash(&self, hash: &Digest256) -> Option<&EldersInfo> {
+        self.state.our_info_by_hash(hash)
+    }
+
+    /// Returns all neighbour elders.
+    // WIP: consider remove
```
[the remark this answers is not in the document]
Comment (madadam) [reply src/chain/chain.rs]: This has been there before this PR. I only moved it to a separate impl block.

File: src/states/elder/mod.rs (hunk 12 above)
Comment (madadam) [reply src/states/elder/mod.rs]: If the new member is going to be immediately promoted to elder (in case of Online) or if the removed member is elder (in case of Offline), then we can't vote `Relocate` there because the `churn_in_progress` flag is set to true. That's why we have to vote in `handle_section_info` because the flag is set to false here. On the other hand, for non-elder members, we can vote directly in `handle_online` / `handle_offline`, although that will only happen when promotions/demotions are implemented.

File: src/states/elder/mod.rs (hunk 13 above)
Comment (madadam) [reply src/states/elder/mod.rs]: In might seem it should be sufficient to only take the proof for the target section, but what can happen (at least in theory) is that the relocating node is not fully caught up to all the changes in its own section (the source section) while the target section already is. So the `proof_for_source` might actually end up being longer than `proof_for_target`. If we didn't do this, the relocating node might not be able to verify the proof.

Also, just taking the longer of the proofs should be guaranteed to be sufficient both for the source and the target.

@jeanphilippeD : could you confirm this?

Comment (jeanphilippeD) [reply src/states/elder/mod.rs]: Yes, we need the longest so it can be validated by both the Relocating node and the target section.
A short comment is probably a good idea.

Comment (madadam) [reply src/states/elder/mod.rs]: OK, I'll add the comment saying something along the same lines as I wrote above you.

File: src/chain/shared_state.rs (hunk 10 above)
Comment (jeanphilippeD) [reply src/chain/shared_state.rs]: I'm thinking if it is not necessary because it is handled somewhere else already we should not try to prune it here. is this performance improvement? seems premature.

Comment (madadam) [reply src/chain/shared_state.rs]: This is already gone. I'm doing the check in `poll_relocation` now which covers both splits and nodes going offline.

File: src/states/adult.rs [hunk 15]
```diff
@@ -501,17 +528,29 @@ impl Approved for Adult {
             })
         } else {
             debug!("{} - Unhandled SectionInfo event", self);
+
+            // Need to pop the relocate queue even though we are not going to vote. Otherwise it
+            // could get out of sync with the rest of the section when we transition to elder.
+            if elders_info.prefix().matches(self.name()) {
+                let _ = self.chain.poll_relocation();
```
Comment (jeanphilippeD) [inline src/states/adult.rs]: Should it be within an if? what happen after a split when one side will get its elder_info, and the other side will get the same elder_info that is not theirs?

File: src/states/elder/mod.rs [hunk 16]
```diff
@@ -335,7 +328,7 @@ impl Elder {
             }
         }
         if let Some(merged_info) = self.chain.try_merge()? {
-            self.vote_for_section_info(merged_info)?;
+            self.vote_for_signed_event(merged_info)?;
```
Comment (jeanphilippeD) [inline src/states/elder/mod.rs]: No response to https://github.com/maidsafe/routing/pull/1866#discussion_r338539462

File: src/states/elder/mod.rs [hunk 17]
```diff
@@ -1575,6 +1560,10 @@ impl Approved for Elder {
             });
 
             self.send_neighbour_infos();
+
+            if let Some(relocate_details) = self.chain.poll_relocation() {
```
Comment (jeanphilippeD) [inline src/states/elder/mod.rs]: Again, should this happen even if not our section we update (Is NeighbourInfo causing trouble, probably not).

File: src/states/adult.rs (hunk 15 above)
Comment (madadam) [reply src/states/adult.rs]: Good point, but I think it still works as is, although possibly not optimally. What happens is that one half of the section processes the next relocation immediately but the other half only on the next self-SectionInfo. Everything is still consistent within each section though. 

I had an idea (and I think you had a similar one) to use the churn_event_backlog also for relocations which I think would solve this issue too (and also make things a bit cleaner). Something for a followup PR perhaps?

File: src/states/elder/mod.rs (hunk 17 above)
Comment (madadam) [reply src/states/elder/mod.rs]: See https://github.com/maidsafe/routing/pull/1866#discussion_r343024335

File: src/states/adult.rs (hunk 15 above)
Comment (jeanphilippeD) [reply src/states/adult.rs]: Yes, make sense

File: src/states/elder/mod.rs [hunk 18]
```diff
@@ -1551,6 +1531,15 @@ impl Approved for Elder {
 
         let self_sec_update = elders_info.prefix().matches(self.name());
 
+        // Poll the relocate queue before the parsec reset, so it is not blocked waiting for the
+        // genesis event. Cast the actual votes only after the parsec reset however, so they already
+        // go to the new instance.
+        let relocate_details = if self_sec_update {
```
Comment (jeanphilippeD) [inline src/states/elder/mod.rs]: That seem a bit weird, But I guess it can be fixed when poll relocation happen in a single place.

File: src/states/adult.rs [hunk 19]
```diff
@@ -234,6 +240,32 @@ impl Adult {
...
+        &mut self,
+        pub_id: PublicId,
+        outbox: &mut dyn EventBox,
+    ) -> Result<(), RoutingError> {
+        let _ = self.chain.add_elder(pub_id)?;
+        self.send_event(Event::NodeAdded(*pub_id.name()), outbox);
+
+        // If the elder being added is us, start sending parsec gossips.
+        if pub_id == *self.id() {
+            self.parsec_timer_token = self.timer.schedule(GOSSIP_TIMEOUT);
```
[the remark this answers is not in the document]
Comment (madadam) [reply src/states/adult.rs]: Poke happens much less frequently and it was causing issues. Can't remember the exact details anymore though. Might not be needed, but it wasn't part of this PR anyway.

File: src/states/elder/mod.rs (hunk 18 above)
Comment (madadam) [reply src/states/elder/mod.rs]: It's a quick and simple fix. We can always refactor later.

**Comment by jeanphilippeD** [comment]
@madadam I won't be there tomorrow, but I'm happy with the state of that PR, even if there need some additional fixes @fizyk20 can review them and if soak test are passing (mock + mock_base) overnight, I'm happy for it to be merged.

File: src/states/joining_peer.rs [hunk 20]
```diff
@@ -32,9 +32,7 @@ use std::{
 };
 
 /// Time after which bootstrap is cancelled (and possibly retried).
-pub const JOIN_TIMEOUT: Duration = Duration::from_secs(120);
```
Comment (jeanphilippeD) [inline src/states/joining_peer.rs]: `This happens because the `completed_events` container in the chain accumulator is not shared state (maybe it should be?)` as you found out this is not ok. Does this patch still make sense/should we revert it too?

File: src/states/elder/mod.rs [hunk 21]
```diff
@@ -1647,26 +1647,29 @@ impl Approved for Elder {
...
-            let proof_for_source = self.chain.prove(&Authority::Node(*details.pub_id.name()));
-            let proof_for_target = self.chain.prove(&Authority::Section(details.destination));
-
-            if proof_for_source.blocks_len() > proof_for_target.blocks_len() {
-                proof_for_source
-            } else {
-                proof_for_target
-            }
-        };
+        // Do not send the message to ourselves.
```
Comment (jeanphilippeD) [inline src/states/elder/mod.rs]: I am not clear this patch makes complete sense.
Other nodes still have the ConnectionInfo, and will also try to send that message. My understanding is that if the node already received one from one node, the section node will try to connect to send that message leading the the same outcome as when node sends to itself.

Shouldn't we check it is a bootstrap node that is connected before sending boostrap request instead?

File: src/states/joining_peer.rs (hunk 20 above)
Comment (madadam) [reply src/states/joining_peer.rs]: I decided to remove the join attempts for two reasons:
1. It was the trigger for the failure mode described in the commit message
2. It was no longer necessary, as the churn serializatin should take care of the issue that it was originally meant to fix. That is, the join attempts were a workaround for a situation where a `JoinRequest` got ignored due to ongoing churn in the target section. With churn serialization this should not happen anymore and so this workaround is not necessary and would only add additional complexity to the code

File: src/states/elder/mod.rs (hunk 21 above)
Comment (madadam) [reply src/states/elder/mod.rs]: > I am not clear this patch makes complete sense.
The main issue is that we currently send `BootstrapRequest` to whoever gets connected to us first. If it happens to be us (how that can happen is described in the commit message), then we are stuck, because we are not going to respond to it. If it is anyone else, even someone from our old section, then in the worst case we get `Rebootstrap` response and proceed normally. So this patch is just a minimal fix to make sure we never send a message to ourselves to prevent this problem.

A more robust fix would be to make sure that we only send `BootstrapRequest` to someone we explicitly connected to via `bootstrap` or `connect_to` and ignore the rest. So basically what you suggest in the last paragraph. Maybe we can use the `nodes_to_await` collection for that somehow. I would handle it in a separate PR as I'm trying to minimize the amount of changes going into this already huge PR. Is that OK with you?

File: src/states/joining_peer.rs (hunk 20 above)
Comment (jeanphilippeD) [reply src/states/joining_peer.rs]: OK, I'm on board with the idea of simplifying. I'm not 100% `no longer necessary` is correct.
(Probably need to fix commit comment because it mention something that no longer is part of the history).

File: src/states/elder/mod.rs (hunk 21 above)
Comment (jeanphilippeD) [reply src/states/elder/mod.rs]: If you think that is ok, I'm happy re-think it later.

File: src/states/joining_peer.rs (hunk 20 above)
Comment (madadam) [reply src/states/joining_peer.rs]: > I'm not 100% no longer necessary is correct.

I'm not 100% either, but pretty close. Previously what could happen is that a joining node would send `JoinRequest` which the section received and voted `Online`. But due to other ongoing churn this vote might have never accumulated. The join attempts were a workaround for this, so the joining node would send the `JoinRequest` again, hoping that the section has stabilized enough to be able to handle it. With churn serialization, my impression is this **should** not be necessary. Or can you think of a case where the join attempts would still be needed?

One issue is that it can take some time for the section to respond to the joining node (due to churn backlogging) which is why I increased the join timeout.

> Probably need to fix commit comment because it mention something that no longer is part of the history

Not sure what you mean by this. What is no longer part of the history?

Comment (jeanphilippeD) [reply src/states/joining_peer.rs]: > This happens because the completed_events container in the chain accumulator is not shared state (maybe it should be?)

Comment (jeanphilippeD) [reply src/states/joining_peer.rs]: (keep on Ctrl Enter to make new line)... I thought you you removed that commit that kept completed_events and made them not shared state.

Comment (madadam) [reply src/states/joining_peer.rs]: Hm, after some time thinking about this, I think you are right. The comment is outdated. Also this whole commit is not really needed. The failure happened because of not resetting the completed_events cache on every parsec reset while also not making it part of shared state. As I removed that commit, that particular failure mode should not be possible anymore. I think this commit is still useful to simplify things, but not essential anymore. So what do you think: should I remove the commit or just edit the commit message?

Comment (jeanphilippeD) [reply src/states/joining_peer.rs]: I leave you to decide. Whatever makes getting all soak test passing (for mock at least) fastest.

File: src/states/bootstrapping_peer.rs [hunk 22]
```diff
@@ -310,15 +268,9 @@ impl Base for BootstrappingPeer {
...
-        conn_info: ConnectionInfo,
+        _conn_info: ConnectionInfo,
         _outbox: &mut dyn EventBox,
     ) -> Transition {
-        debug!(
-            "{} Received ConnectedTo event from {}.",
-            self, conn_info.peer_addr
-        );
-
-        self.send_bootstrap_request(conn_info);
```
Comment (jeanphilippeD) [inline src/states/bootstrapping_peer.rs]: Can you explain why we did that, and we no longer need to?

File: src/states/bootstrapping_peer.rs [hunk 23]
```diff
@@ -291,8 +289,16 @@ impl Base for BootstrappingPeer {
         p2p_node: P2pNode,
         _: &mut dyn EventBox,
     ) -> Result<Transition, RoutingError> {
-        // TODO: ignore messages from peers we don't send `BootstrapRequest` to and disconnect
-        // from them.
+        // Ignore messages from peers we didn't send `BootstrapRequest` to.
```
Comment (jeanphilippeD) [inline src/states/bootstrapping_peer.rs]: Should we disconnect earlier, i.e when we get a connected_to?
Is there a way to ensure that we won't completely receive the message sent to us so the sender know it failed, otherwise, we are not really suppose to drop it as it could be a signature accumulation or other things, but maybe it is ok for now and we can look at it later.

**Comment by jeanphilippeD** [comment]
New commit looks good.

File: src/states/bootstrapping_peer.rs (hunk 22 above)
Comment (madadam) [reply src/states/bootstrapping_peer.rs]: The previous flow was:
1. initiate connection to the bootstrapping nodes
2. wait for `ConnectedTo` from them
3. send `BootstrapRequest` when we receive it

Now this changes to simply:
1. send `BootstrapRequest` 

So we don't need to do anything in `handle_connected_to` anymore.

File: src/states/bootstrapping_peer.rs (hunk 23 above)
Comment (madadam) [reply src/states/bootstrapping_peer.rs]: > Should we disconnect earlier, i.e when we get a connected_to?

Yeah, that would possibly be a bit more robust.

> Is there a way to ensure that we won't completely receive the message sent to us so the sender know it failed, 

Hm, I'm not sure. Ideally the nodes in the source section would not try to send any messages to the relocated node once they know that it got relocated (so once `Relocate` is accumulated, not just once `SectionInfo` is). Not sure we can do that.

> we are not really suppose to drop it as it could be a signature accumulation

We are not member of the section anymore, so what else are we supposed to do?

Comment (jeanphilippeD) [reply src/states/bootstrapping_peer.rs]: > m, I'm not sure. Ideally the nodes in the source section would not try to send any messages to the relocated node once they know that it got relocated 

=> Yes, it could also be from other section relaying message.

> We are not member of the section anymore, so what else are we supposed to do?

=> Tricky, not sure, for RoutingMessage, easier, we could send them to all the node we knew as elder, for DirectMessage, that seem difficult to do anything, Maybe we still process them in some way. For example, we may have been sig accumulating and waiting for additional signatures, then we get a new one after we Relocated (because other node was late), then we probably should finish accumulation and send that message, maybe could send it to all elders of section we were at?
=> It may also become less of an issue with node ageing if we don't imediatly relocate elder, i.e we leave them to cool down for a while as non participating node that complete whatever they were doing, and after enough time that we are unlikely to get message we need to process then we relocate.

Comment (madadam) [reply src/states/bootstrapping_peer.rs]: OK, so what about addressing this only when node ageing is in place? Or do you think this causes issue right now?

Comment (jeanphilippeD) [reply src/states/bootstrapping_peer.rs]: "but maybe it is ok for now and we can look at it later."
I think if we don't get error we can leave it. and yes addressing it with node ageing is probably easier. (But if we get error from message it could also come from there).
