### PR TITLE
Fixes #506 and Optional Signature for StructuredData

### LINKED ISSUE #506: ownership can be transferred without proper signature from previous_owner
The following test will be failed in routing::structured_data, which indicates the signature part doesn't get properly checked to transfer the ownership
    #[test]
    fn transfer_owner() {
        let keys1       = crypto::sign::gen_keypair();
        let keys2       = crypto::sign::gen_keypair();
        let keys3       = crypto::sign::gen_keypair();
        let identifier : NameType = Random::generate_random();
        let data = generate_random_vec_u8(1024);
        let mut sd = StructuredData::new(0, identifier, data.clone(), vec![], 0, vec![keys1.0], vec![]);
        let _ = sd.add_signature(&keys1.1);
        let mut sd_new = StructuredData::new(0, identifier, data.clone(), vec![keys1.0], 1, vec![keys2.0], vec![]);
        assert_eq!(sd_new.add_signature(&keys3.1).ok(), Some(0));
        match sd.replace_with_other(sd_new) {
            Ok(_) => panic!("unexpected!"),
            Err(_) => {}
        }
    }

### PR DESCRIPTION
**Pull request by ustulation**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/611)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @inetic

(maidsafe_highfive has picked a reviewer for you, use r? to override)

File: src/structured_data.rs [hunk 1]
```diff
@@ -57,7 +57,9 @@ impl StructuredData {
                    previous_owner_signatures: vec![],
                  };
 
-        let _ = try!(structured_data.add_signature(signing_key));
+        if let Some(key) = signing_key {
```
Comment (dirvine) [inline src/structured_data.rs]: :+1:

**Comment by benjaminbollen** [comment]
looks good to me
